.PHONY: preview

help:
	@echo "Available targets:"
	@echo "preview        preview infrastructure changes"
	@echo "up             apply infrastructure changes"

preview:
	pulumi preview

up:
	pulumi up
